export const COURSE = {
  code: "CSE445",
  title: "Computer Vision",
  semester: "Summer 2026",
  credits: 4,
  theoryCredits: 3,
  labCredits: 1,
  contactHours: "Theory: 3 hrs/week x 13 weeks + Final Exam; Lab: 2 hrs/week x 14 weeks",
  department: "Department of Computer Science and Engineering",
  university: "East West University",
  instructor: "Dr. Mohammad Rifat Ahmmad Rashid",
  instructorShort: "Dr. Md. Rifat Ahmmad Rashid",
  designation: "Associate Professor, Department of CSE, East West University",
  office: "Room #646",
  email: "rifat.rashid@ewubd.edu",
  totalLectures: 21,
  totalLabWeeks: 10,
  totalCOs: 4,
  totalMarks: 100,
  prerequisite: "CSE246 - Algorithms",
};
